services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    configs:
      - source: mosquitto_config
        target: /mosquitto/config/mosquitto.conf
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    networks:
      - iot_net

  nodered:
    image: nodered/node-red:latest
    container_name: nodered
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - nodered_data:/data
    depends_on:
      - mosquitto
    networks:
      - iot_net

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    ports:
      - "8123:8123"
    volumes:
      - homeassistant_data:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Zurich
    depends_on:
      - mosquitto
    networks:
      - iot_net

configs:
  mosquitto_config:
    content: |
      listener 1883
      allow_anonymous true

      listener 9001
      protocol websockets
      allow_anonymous true

volumes:
  mosquitto_data:
  mosquitto_log:
  nodered_data:
  homeassistant_data:

networks:
  iot_net:
    driver: bridge
